// <auto-generated />
using System;
using KargoTakipSistemi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KargoTakipSistemi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KargoTakipSistemi.Models.DurumKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("KargoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KargoId");

                    b.ToTable("DurumKayitlari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Kargo Merkez Şube tarafından teslim alındı.",
                            Durum = "Kargo alındı",
                            KargoId = 1,
                            Tarih = new DateTime(2026, 5, 20, 9, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Kargo İstanbul Transfer Merkezi'ne yönlendirildi.",
                            Durum = "Transfer merkezinde",
                            KargoId = 1,
                            Tarih = new DateTime(2026, 5, 21, 14, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Kargo alıcı adresine teslim edilmek üzere dağıtıma çıkarıldı.",
                            Durum = "Dağıtıma çıktı",
                            KargoId = 1,
                            Tarih = new DateTime(2026, 5, 24, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Kargo göndericiden teslim alındı.",
                            Durum = "Kargo alındı",
                            KargoId = 2,
                            Tarih = new DateTime(2026, 5, 21, 11, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Aciklama = "Kargo Ankara Dağıtım Şubesi'ne sevk edildi.",
                            Durum = "Transfer merkezinde",
                            KargoId = 2,
                            Tarih = new DateTime(2026, 5, 22, 16, 20, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Aciklama = "Kargo Konya Şubesi tarafından teslim alındı.",
                            Durum = "Kargo alındı",
                            KargoId = 3,
                            Tarih = new DateTime(2026, 5, 22, 8, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Aciklama = "Kargo alıcı adresine teslim için dağıtıma çıkarıldı.",
                            Durum = "Dağıtıma çıktı",
                            KargoId = 3,
                            Tarih = new DateTime(2026, 5, 24, 9, 10, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Aciklama = "Kargo alıcıya başarıyla teslim edildi.",
                            Durum = "Teslim edildi",
                            KargoId = 3,
                            Tarih = new DateTime(2026, 5, 24, 15, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Aciklama = "Kargo Ankara Dağıtım Şubesi tarafından sisteme kaydedildi.",
                            Durum = "Kargo alındı",
                            KargoId = 4,
                            Tarih = new DateTime(2026, 5, 23, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Aciklama = "Kargo Karaman Merkez Şube'ye yönlendirildi.",
                            Durum = "Transfer merkezinde",
                            KargoId = 4,
                            Tarih = new DateTime(2026, 5, 24, 9, 50, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Aciklama = "Kargo İzmir Şubesi tarafından teslim alındı.",
                            Durum = "Kargo alındı",
                            KargoId = 5,
                            Tarih = new DateTime(2026, 5, 18, 10, 20, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Aciklama = "Kargo alıcı adresine dağıtıma çıkarıldı.",
                            Durum = "Dağıtıma çıktı",
                            KargoId = 5,
                            Tarih = new DateTime(2026, 5, 21, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Aciklama = "Kargo teslim edildi.",
                            Durum = "Teslim edildi",
                            KargoId = 5,
                            Tarih = new DateTime(2026, 5, 21, 16, 10, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            Aciklama = "Kargo Bursa Dağıtım Merkezi'ne kaydedildi.",
                            Durum = "Kargo alındı",
                            KargoId = 6,
                            Tarih = new DateTime(2026, 5, 19, 12, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            Aciklama = "Kargo transfer işlemi için bekliyor.",
                            Durum = "Transfer merkezinde",
                            KargoId = 6,
                            Tarih = new DateTime(2026, 5, 20, 17, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            Aciklama = "Kargo Antalya Şubesi tarafından teslim alındı.",
                            Durum = "Kargo alındı",
                            KargoId = 7,
                            Tarih = new DateTime(2026, 5, 20, 15, 10, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            Aciklama = "Kargo şehir içi dağıtım merkezine gönderildi.",
                            Durum = "Transfer merkezinde",
                            KargoId = 7,
                            Tarih = new DateTime(2026, 5, 21, 10, 35, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            Aciklama = "Kargo kurye tarafından dağıtıma çıkarıldı.",
                            Durum = "Dağıtıma çıktı",
                            KargoId = 7,
                            Tarih = new DateTime(2026, 5, 22, 8, 50, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            Aciklama = "Kargo Adana Transfer Şubesi tarafından alındı.",
                            Durum = "Kargo alındı",
                            KargoId = 8,
                            Tarih = new DateTime(2026, 5, 17, 9, 25, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            Aciklama = "Kargo alıcıya teslim edildi.",
                            Durum = "Teslim edildi",
                            KargoId = 8,
                            Tarih = new DateTime(2026, 5, 20, 14, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            Aciklama = "Kargo Kayseri Şubesi tarafından sisteme eklendi.",
                            Durum = "Kargo alındı",
                            KargoId = 9,
                            Tarih = new DateTime(2026, 5, 21, 13, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            Aciklama = "Kargo transfer merkezinde işlem görüyor.",
                            Durum = "Transfer merkezinde",
                            KargoId = 9,
                            Tarih = new DateTime(2026, 5, 22, 18, 5, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            Aciklama = "Kargo Trabzon Şubesi tarafından teslim alındı.",
                            Durum = "Kargo alındı",
                            KargoId = 10,
                            Tarih = new DateTime(2026, 5, 22, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            Aciklama = "Kargo bölgesel transfer merkezine gönderildi.",
                            Durum = "Transfer merkezinde",
                            KargoId = 10,
                            Tarih = new DateTime(2026, 5, 23, 10, 25, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            Aciklama = "Kargo İstanbul Transfer Merkezi'nde kayıt altına alındı.",
                            Durum = "Kargo alındı",
                            KargoId = 11,
                            Tarih = new DateTime(2026, 5, 23, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            Aciklama = "Kargo dağıtıma çıkarıldı.",
                            Durum = "Dağıtıma çıktı",
                            KargoId = 11,
                            Tarih = new DateTime(2026, 5, 24, 13, 10, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            Aciklama = "Kargo Ankara Dağıtım Şubesi'nde teslim alındı.",
                            Durum = "Kargo alındı",
                            KargoId = 12,
                            Tarih = new DateTime(2026, 5, 24, 10, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            Aciklama = "Kargo teslimat öncesi transfer merkezinde bekliyor.",
                            Durum = "Transfer merkezinde",
                            KargoId = 12,
                            Tarih = new DateTime(2026, 5, 25, 9, 20, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            Aciklama = "Kargo İzmir Şubesi tarafından alındı.",
                            Durum = "Kargo alındı",
                            KargoId = 13,
                            Tarih = new DateTime(2026, 5, 24, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            Aciklama = "Kargo şehir içi transfer sürecinde.",
                            Durum = "Transfer merkezinde",
                            KargoId = 13,
                            Tarih = new DateTime(2026, 5, 25, 11, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            Aciklama = "Kargo Bursa Dağıtım Merkezi'ne teslim edildi.",
                            Durum = "Kargo alındı",
                            KargoId = 14,
                            Tarih = new DateTime(2026, 5, 25, 8, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            Aciklama = "Kargo transfer merkezinde işleme alındı.",
                            Durum = "Transfer merkezinde",
                            KargoId = 14,
                            Tarih = new DateTime(2026, 5, 25, 15, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            Aciklama = "Kargo Merkez Şube tarafından teslim alındı.",
                            Durum = "Kargo alındı",
                            KargoId = 15,
                            Tarih = new DateTime(2026, 5, 25, 9, 10, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            Aciklama = "Kargo dağıtım için hazırlanıyor.",
                            Durum = "Transfer merkezinde",
                            KargoId = 15,
                            Tarih = new DateTime(2026, 5, 25, 12, 50, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            Aciklama = "Kargo alıcı adresine teslim edilmek üzere dağıtıma çıkarıldı.",
                            Durum = "Dağıtıma çıktı",
                            KargoId = 15,
                            Tarih = new DateTime(2026, 5, 26, 9, 30, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("KargoTakipSistemi.Models.Kargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AliciAd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AliciAdres")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("GondericiAd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("GonderimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubeId")
                        .HasColumnType("int");

                    b.Property<string>("TakipNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("TeslimTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SubeId");

                    b.ToTable("Kargolar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AliciAd = "Ayşe Yılmaz",
                            AliciAdres = "İstanbul / Kadıköy",
                            GondericiAd = "Zülal Doğu",
                            GonderimTarihi = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubeId = 1,
                            TakipNo = "KRG001"
                        },
                        new
                        {
                            Id = 2,
                            AliciAd = "Elif Demir",
                            AliciAdres = "Ankara / Çankaya",
                            GondericiAd = "Mehmet Kaya",
                            GonderimTarihi = new DateTime(2026, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubeId = 2,
                            TakipNo = "KRG002"
                        },
                        new
                        {
                            Id = 3,
                            AliciAd = "Ahmet Koç",
                            AliciAdres = "Konya / Selçuklu",
                            GondericiAd = "Fatma Şahin",
                            GonderimTarihi = new DateTime(2026, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubeId = 4,
                            TakipNo = "KRG003",
                            TeslimTarihi = new DateTime(2026, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            AliciAd = "Merve Aydın",
                            AliciAdres = "Karaman / Merkez",
                            GondericiAd = "Can Arslan",
                            GonderimTarihi = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubeId = 3,
                            TakipNo = "KRG004"
                        },
                        new
                        {
                            Id = 5,
                            AliciAd = "Burak Yıldız",
                            AliciAdres = "İzmir / Bornova",
                            GondericiAd = "Selin Aksoy",
                            GonderimTarihi = new DateTime(2026, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubeId = 5,
                            TakipNo = "KRG005",
                            TeslimTarihi = new DateTime(2026, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            AliciAd = "Deniz Kurt",
                            AliciAdres = "Bursa / Nilüfer",
                            GondericiAd = "Emre Çelik",
                            GonderimTarihi = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubeId = 6,
                            TakipNo = "KRG006"
                        },
                        new
                        {
                            Id = 7,
                            AliciAd = "Hakan Öz",
                            AliciAdres = "Antalya / Muratpaşa",
                            GondericiAd = "Gamze Polat",
                            GonderimTarihi = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubeId = 7,
                            TakipNo = "KRG007"
                        },
                        new
                        {
                            Id = 8,
                            AliciAd = "Seda Kılıç",
                            AliciAdres = "Adana / Seyhan",
                            GondericiAd = "Ali Yavuz",
                            GonderimTarihi = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubeId = 8,
                            TakipNo = "KRG008",
                            TeslimTarihi = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            AliciAd = "Onur Eren",
                            AliciAdres = "Kayseri / Melikgazi",
                            GondericiAd = "Buse Acar",
                            GonderimTarihi = new DateTime(2026, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubeId = 9,
                            TakipNo = "KRG009"
                        },
                        new
                        {
                            Id = 10,
                            AliciAd = "Derya Güneş",
                            AliciAdres = "Trabzon / Ortahisar",
                            GondericiAd = "Kerem Uslu",
                            GonderimTarihi = new DateTime(2026, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubeId = 10,
                            TakipNo = "KRG010"
                        },
                        new
                        {
                            Id = 11,
                            AliciAd = "Tolga Can",
                            AliciAdres = "İstanbul / Beşiktaş",
                            GondericiAd = "Ece Yıldırım",
                            GonderimTarihi = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubeId = 2,
                            TakipNo = "KRG011"
                        },
                        new
                        {
                            Id = 12,
                            AliciAd = "Nazlı Ersoy",
                            AliciAdres = "Ankara / Keçiören",
                            GondericiAd = "Furkan Taş",
                            GonderimTarihi = new DateTime(2026, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubeId = 3,
                            TakipNo = "KRG012"
                        },
                        new
                        {
                            Id = 13,
                            AliciAd = "Cem Avcı",
                            AliciAdres = "İzmir / Karşıyaka",
                            GondericiAd = "Melis Kara",
                            GonderimTarihi = new DateTime(2026, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubeId = 5,
                            TakipNo = "KRG013"
                        },
                        new
                        {
                            Id = 14,
                            AliciAd = "İrem Bulut",
                            AliciAdres = "Bursa / Osmangazi",
                            GondericiAd = "Oğuzhan Demir",
                            GonderimTarihi = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubeId = 6,
                            TakipNo = "KRG014"
                        },
                        new
                        {
                            Id = 15,
                            AliciAd = "Yusuf Arı",
                            AliciAdres = "Karaman / Üniversite Mahallesi",
                            GondericiAd = "Nisa Kaplan",
                            GonderimTarihi = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubeId = 1,
                            TakipNo = "KRG015"
                        });
                });

            modelBuilder.Entity("KargoTakipSistemi.Models.Sube", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Sehir")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SubeAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Subeler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adres = "Merkez Mahallesi Atatürk Bulvarı No:10",
                            Sehir = "Karaman",
                            SubeAdi = "Merkez Şube",
                            Telefon = "0338 212 00 01"
                        },
                        new
                        {
                            Id = 2,
                            Adres = "Esenler Lojistik Bölgesi No:45",
                            Sehir = "İstanbul",
                            SubeAdi = "İstanbul Transfer Merkezi",
                            Telefon = "0212 555 34 34"
                        },
                        new
                        {
                            Id = 3,
                            Adres = "Çankaya Mahallesi Tunus Caddesi No:18",
                            Sehir = "Ankara",
                            SubeAdi = "Ankara Dağıtım Şubesi",
                            Telefon = "0312 444 06 06"
                        },
                        new
                        {
                            Id = 4,
                            Adres = "Selçuklu Mahallesi Lojistik Sokak No:7",
                            Sehir = "Konya",
                            SubeAdi = "Konya Şubesi",
                            Telefon = "0332 222 11 22"
                        },
                        new
                        {
                            Id = 5,
                            Adres = "Bornova Mahallesi Kargo Caddesi No:21",
                            Sehir = "İzmir",
                            SubeAdi = "İzmir Şubesi",
                            Telefon = "0232 333 45 45"
                        },
                        new
                        {
                            Id = 6,
                            Adres = "Nilüfer Organize Sanayi Bölgesi No:9",
                            Sehir = "Bursa",
                            SubeAdi = "Bursa Dağıtım Merkezi",
                            Telefon = "0224 555 12 12"
                        },
                        new
                        {
                            Id = 7,
                            Adres = "Muratpaşa Mahallesi Lojistik Bulvarı No:16",
                            Sehir = "Antalya",
                            SubeAdi = "Antalya Şubesi",
                            Telefon = "0242 444 07 07"
                        },
                        new
                        {
                            Id = 8,
                            Adres = "Seyhan Mahallesi Kargo Sokak No:5",
                            Sehir = "Adana",
                            SubeAdi = "Adana Transfer Şubesi",
                            Telefon = "0322 666 23 23"
                        },
                        new
                        {
                            Id = 9,
                            Adres = "Melikgazi Mahallesi Sanayi Caddesi No:30",
                            Sehir = "Kayseri",
                            SubeAdi = "Kayseri Şubesi",
                            Telefon = "0352 777 18 18"
                        },
                        new
                        {
                            Id = 10,
                            Adres = "Ortahisar Mahallesi Liman Caddesi No:11",
                            Sehir = "Trabzon",
                            SubeAdi = "Trabzon Şubesi",
                            Telefon = "0462 888 61 61"
                        });
                });

            modelBuilder.Entity("KargoTakipSistemi.Models.DurumKaydi", b =>
                {
                    b.HasOne("KargoTakipSistemi.Models.Kargo", "Kargo")
                        .WithMany("DurumKayitlari")
                        .HasForeignKey("KargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kargo");
                });

            modelBuilder.Entity("KargoTakipSistemi.Models.Kargo", b =>
                {
                    b.HasOne("KargoTakipSistemi.Models.Sube", "Sube")
                        .WithMany("Kargolar")
                        .HasForeignKey("SubeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sube");
                });

            modelBuilder.Entity("KargoTakipSistemi.Models.Kargo", b =>
                {
                    b.Navigation("DurumKayitlari");
                });

            modelBuilder.Entity("KargoTakipSistemi.Models.Sube", b =>
                {
                    b.Navigation("Kargolar");
                });
#pragma warning restore 612, 618
        }
    }
}
